language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: ItKnrJ0t80wT3Eq9BjVOdT28OwchU4LJLPZfgy6DT17hX9pQ8D1gV+KjXRjiniuhOtbygmzW/56MseG9az7AeL4hnYo0+9Bz2ZxnxOUybjuj+iamMQaPvEYT2ZUbgkZXXNqB7Iwej5K9gPj8iHOa+b+qPqC6fXCjsuI+c5Uy/7b7XvOV4fuogtqcErqGEopSa0kjnFGphA01s2/jy9T4OXx09M5C5hY92spBUwZj6/C+b3/Gak9N/xo1yPA10y8i43gzm16NvvBne9qlrddtSEk3Yt2+lDjHVv1RZ1giaAqKNZFx+kRBAfXgQWX9hoMrPQhVqa6mu+I0diUTEREgw4PBpD9+7H4jKtpTlwbA57GVmVW3A7BzD1T2Gq/amt7D8ScCU6ZEUBzfk21/XyQvmpxTDW43z4nfzcZT5wZQsvlX+0BSYKCjs8yGVomj5+90E21dtkuXX0+6cHkZsZD5t5tYEN/qyvvgliYIJvET/DSkXwjbh/HA7WhMvQYCZqVysnAm34Vmk+/uGpCjnRXnUSh4w4pm9kSEqMTL7DGKL4HTaH5zDYxASB99CMyQ8tjejPHKQJeELYAamiqJgi3Lmmopqaeur2cmVmdJP6CWKKbwIHQCkCVtmCvbEuI17qlCTceV6DSAIXcr0cFckOmFirHWrURO/s6j/TMeCfu6IfU=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: GN/eSIEo1TLmGbTPh6b2SBri7epwpM/qrIw2XgP9AKD0vT/0w7GXxx5Ya+j2YQzXw9XTMrcoeo0Soz3HP0ei9gtbQsSC3x1WCOu7MHb5RbNczZlH81DzUGHauxWwJYhtbd3wZRWdJoZnZESRipwzsbAZrp7QMz2/6AyVo3LKBVYcKTpR9KWj0olxEgN7sXJGF7FT/nQbgPYM3O/kG1kcsDE/BGdVdR8URQmKcKCAkr1HfEbI+FCTrOkmfB7PtQUq9cvkjSMPwNGBHThwZARE69FnmUOwhRFSp1CyyNMXP9YhMCOZH6lNZ4TFc+3L+gvg9583R6DQm1ivAF+dzl1dg2QkuBOn6e912IJxS0nIv0arxacgkiK0AZ7OP81i79oCwHDFow88xAeI5WymL6GKyUFyBX81KggP2A3C47WrfisPU8IgJKY8fXsF+nesrDmOrjpq2P5J/o5vrkD7PJnS+4PTAvstfSgWNpLADC9nIUXenMwEd7nAHOjQiC61NNi6/VaWQJZKRVSPdF+EGRp72T6jtOyI/8cpjZmW9dt44Q8tGsP4OXvN3NJYlmmCqM4Uk1giEV6NYO2KPve0T/5RDUNyu0RugvCDGy/yoUUwexVk8UfE7RMWLkoJHvKbM/T8UR+xIOQ3g+14d6D9sh7eCK0R4LxdVyrubpGL2wCkhRs=
sudo: false
